runtime: python311

api_version: 1

handlers:
  - url: /
    static_files: /build/web/index.html
    upload: build/web/index.html

  - url: /(.*)
    static_files: build/web/\1
    upload: build/web/(.*)
