// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7sIBazbcynyrLAFt4D51Ac8DlFKmTwgw',
    appId: '1:501583719435:web:1d98f309ed93d8ba3f2b0e',
    messagingSenderId: '501583719435',
    projectId: 'rellai',
    authDomain: 'rellai.firebaseapp.com',
    storageBucket: 'rellai.appspot.com',
    measurementId: 'G-48B9Z4CY02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjqYWES-uAkLYeUcpYBIkeHOG2SaFUxqs',
    appId: '1:501583719435:android:e770ef7d6cbff5c53f2b0e',
    messagingSenderId: '501583719435',
    projectId: 'rellai',
    storageBucket: 'rellai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0b_nGiSFPy9Br_z0sHJph8eHZEPtFBnE',
    appId: '1:501583719435:ios:7657e9f9daf0b1923f2b0e',
    messagingSenderId: '501583719435',
    projectId: 'rellai',
    storageBucket: 'rellai.appspot.com',
    iosClientId: '501583719435-drsl4491384n23fcs8voja6u74v3t59g.apps.googleusercontent.com',
    iosBundleId: 'com.example.rellaiFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0b_nGiSFPy9Br_z0sHJph8eHZEPtFBnE',
    appId: '1:501583719435:ios:7657e9f9daf0b1923f2b0e',
    messagingSenderId: '501583719435',
    projectId: 'rellai',
    storageBucket: 'rellai.appspot.com',
    iosClientId: '501583719435-drsl4491384n23fcs8voja6u74v3t59g.apps.googleusercontent.com',
    iosBundleId: 'com.example.rellaiFrontend',
  );
}
